name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Setup Java ğŸ› 
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew ğŸ‘®â€
        run: chmod +x gradlew
      - name: Build and run tests ğŸƒâ€
        run: ./gradlew build
      - name: Lint ğŸ§¼
        run: ./gradlew lintKotlin
      - name: Generate Test Report ğŸ§ª
        run: ./gradlew jacocoTestReport
#      - name: Publish Test Report ğŸ“°
#        uses: actions/upload-artifact@v2
#        with:
#          name: report
#          path: app/build/reports/coverage/debug
      - name: Upload Test Report â¬†ï¸
        run: bash <(curl -s https://codecov.io/bash) -f "build/reports/jacoco/report.xml"
      - name: Generate API documentation ğŸ“”
        if: ${{github.event_name == 'push'}}
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages ğŸš¦
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka/html